#!/usr/bin/env python

import socket
import array
import sys

SYSTEM = 0x01
GESCHW = 0x08
RICHTU = 0x0A

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('', 15733))

while True:
	data, adrs = sock.recvfrom(13)
	cmd = int(data[1].encode('hex'), 16)
	subcmd = int(data[9].encode('hex'), 16)

	if (cmd == SYSTEM):
		if (subcmd == 0x00 or subcmd == 0x02 ):
			target = open('/var/www/html/python/caninformation.txt', 'w')
			target.truncate()
			target.write('0')
			target.close()
		if (subcmd == 0x01):
			target = open('/var/www/html/python/caninformation.txt', 'w')
			target.truncate()
			target.write('1')
			target.close()

	if (cmd == GESCHW):
		locid = (int(data[7].encode('hex'), 16) << 8 ) + int(data[8].encode('hex'), 16)
		value = (int(data[9].encode('hex'), 16) << 8 ) + int(data[10].encode('hex'), 16)
		target = open('/var/www/html/python/' + str(locid) + '.txt', 'w')
		target.truncate()
		target.write(str(value))
		target.close()
