#!/usr/bin/env python

import socket
import array
import sys

def argError():
        print "Error!"
        sys.exit()

if len(sys.argv) != 2:
        argError()
elif (sys.argv[1] != "stop") and (sys.argv[1] != "go"):
        argError()

UDP_IP = "127.0.0.1"
UDP_PORT = 15731
MSG_STOP = bytearray([0x00,0x00,0x03,0x00,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00])
MSG_GO =   bytearray([0x00,0x00,0x03,0x00,0x05,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00])

sck = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

if (sys.argv[1] == "stop"):
	sck.sendto(str(MSG_STOP), (UDP_IP, UDP_PORT))
elif (sys.argv[1] == "go"):
	sck.sendto(str(MSG_GO), (UDP_IP, UDP_PORT))
