#!/usr/bin/env python

import socket
import array
import sys

def argError():
        print "Error!"
        sys.exit()

def bytes(integer):
	return divmod(integer, 0x100)

if len(sys.argv) != 3:
        argError()

locid = int(sys.argv[1])
value = int(sys.argv[2])

value_high, value_low = divmod(value, 0x100)
locid_high, locid_low = divmod(locid, 0x100)

UDP_IP = "127.0.0.1"
UDP_PORT = 15731
MSG = bytearray([0x00,0x08,0x03,0x00,0x06,0x00,0x00,locid_high,locid_low,value_high,value_low,0x00,0x00])

sck = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

sck.sendto(str(MSG), (UDP_IP, UDP_PORT))